In [15]:
import numpy as np
import pandas as pd
from sklearn.utils.class_weight import compute_class_weight

In [16]:
train_df = pd.read_csv('../../data/cr_sec_6/train.csv')
train_df

Id  Rating                                 Name Symbol  \
0     1149       3             Vulcan Materials Company    VMC   
1      942       3         Vishay Intertechnology, Inc.    VSH   
2     1006       3         Kennedy-Wilson Holdings Inc.     KW   
3     1977       4  MagnaChip Semiconductor Corporation     MX   
4      253       2         LyondellBasell Industries NV    LYB   
...    ...     ...                                  ...    ...   
1255  1215       2              Black Hills Corporation    BKH   
1256  1120       3           Gibraltar Industries, Inc.   ROCK   
1257   720       2                 Mosaic Company (The)    MOS   
1258  1879       4  Select Medical Holdings Corporation    SEM   
1259    24       1              Duke Energy Corporation    DUK   

                      Rating Agency Name        Date            Sector  \
0              Moody's Investors Service   7/12/2012  Basic Industries   
1     Standard & Poor's Ratings Services    6/1/2012     Capital Goods   
2     Standard & Poor's Ratings Services  12/12/2014           Finance   
3              Moody's Investors Service   6/27/2014        Technology   
4     Standard & Poor's Ratings Services   1/21/2016  Basic Industries   
...                                  ...         ...               ...   
1255           Moody's Investors Service   8/11/2016  Public Utilities   
1256  Standard & Poor's Ratings Services   1/26/2016     Capital Goods   
1257           Moody's Investors Service   6/15/2012  Basic Industries   
1258  Standard & Poor's Ratings Services  11/17/2016       Health Care   
1259          Egan-Jones Ratings Company   9/27/2013  Public Utilities   

      currentRatio  quickRatio  cashRatio  ...  cashPerShare  \
0         2.256983    1.363618   0.631235  ...      2.447563   
1         4.162633    2.885929   1.703293  ...      6.235256   
2         3.225442    3.225442   2.404976  ...     10.585100   
3         2.061519    1.464672   0.947629  ...      4.499237   
4         2.250862    1.000460   0.212463  ...      4.275269   
...            ...         ...        ...  ...           ...   
1255      0.884231    0.532279   0.025723  ...      0.341243   
1256      1.895531    1.261237   0.371412  ...      2.204655   
1257      3.466373    2.649831   2.025616  ...      9.479148   
1258      1.413608    1.176942   0.173238  ...      0.774796   
1259      1.216566    0.389287   0.173646  ...      4.604816   

      companyEquityMultiplier  ebitPerRevenue  enterpriseValueMultiple  \
0                    2.160719       -0.046904                23.455712   
1                    1.867573        0.127645                 3.455541   
2                    7.027078        2.134146                11.711758   
3                    7.667186       -0.082042                93.032349   
4                    3.474351        0.189675                 5.985672   
...                       ...             ...                      ...   
1255                 4.035233        0.059191                15.315972   
1256                 2.169720        0.035643                 9.224703   
1257                 1.356076        0.253426                 8.712714   
1258                 6.061350        0.042168                 9.095279   
1259                 2.777135        0.159363                10.729185   

      operatingCashFlowPerShare  operatingCashFlowSalesRatio  \
0                      1.838028                     0.092889   
1                      2.348851                     0.144963   
2                      1.099765                     1.709059   
3                      1.951482                     0.093649   
4                     12.563441                     0.178463   
...                         ...                          ...   
1255                   6.172008                     0.203731   
1256                   2.775398                     0.083280   
1257                   5.441031                     0.244189   
1258                   2.711

In [17]:
train_df['Rating'].value_counts()

2    409
3    302
1    253
4    180
0     70
5     46
Name: Rating, dtype: int64

In [18]:
train_df['Rating']

0       3
1       3
2       3
3       4
4       2
       ..
1255    2
1256    3
1257    2
1258    4
1259    1
Name: Rating, Length: 1260, dtype: int64

In [19]:
y = train_df['Rating'].values
y

array([3, 3, 3, ..., 2, 4, 1])

In [20]:
classes = np.unique(train_df['Rating'])
classes

array([0, 1, 2, 3, 4, 5])

In [22]:
compute_class_weight(class_weight='balanced', classes=classes, y=y)

array([3.        , 0.83003953, 0.51344743, 0.69536424, 1.16666667,
       4.56521739])